### ISSUE TITLE
where's the release?

### ISSUE THREAD

**Issue by Maxitendo1** [sowa705/AIGallery#1]

**Comment by sowa705** [comment]
when it's done

**Comment by Maxitendo1** [comment]
ok thanks for the fast reply. just came back from this issue, thought it would already work:

https://github.com/slavabarkov/tidy/issues/27#issuecomment-2227043462

**Comment by sowa705** [comment]
There was a change of plans and I'm basically rebuilding old tidy code on a better gallery app as a base

**Comment by sowa705** [comment]
It will take some time for me to fix img2img and release properly (on the play store and here)

**Comment by Maxitendo1** [comment]
Thanks for the info. Good luck!

**Comment by harcesz** [comment]
Fdroid release would also be great! Came here from the same tidy issue.

**Comment by sowa705** [comment]
actually my google play account got closed like a week ago. I'm not in the mood to pay them again so I'm closing this for now
